In [1]:
import numpy as np
from PIL import Image
import cv2
import time
import pyautogui
import keyboard

import torch
from torchvision import transforms
from torchvision import models


width = 480
height = 270


    
def forward():
    keyboard.press('w')
    time.sleep(0.04)
    keyboard.release('w')

def left():
    keyboard.press('a')
    keyboard.press('w')
    time.sleep(0.04)
    keyboard.release('a')
    keyboard.release('w')

def right():
    keyboard.press('d')
    keyboard.press('w')
    time.sleep(0.04)
    keyboard.release('d')
    keyboard.release('w')
    
def brake():
    keyboard.press('s')
    time.sleep(0.04)
    keyboard.release('s')



# Load trained ResNet-50 model
model = models.resnet50(weights=None)
model.fc = torch.nn.Linear(model.fc.in_features, 4)  # 4 outputs - brake, forward, left, right
model.load_state_dict(torch.load('models/modelname.type', map_location=torch.device('cuda')))
model.eval()

for i in range(5, 0, -1):       
        print(f"Time left: {i} seconds", end='\r')
        time.sleep(1) 


# Pause to change to GTA windows
time.sleep(4)

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((480, 270)),
    transforms.ToTensor(),
])

# Initialize the camera
cap = cv2.VideoCapture(0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print("running ResNet auto-pilot...................")
def main():
    
    while True:

        ret, frame = cap.read()

        if not ret:
            break

        frame = cv2.resize(frame, (width, height))
        cv2.imshow('camera', frame)
        screen_img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        screen_img = transform(screen_img).unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(screen_img)
            _, predicted = torch.max(output, 1)
            prediction = predicted.item()
            
            #print probas
            # print("Probass:", output)
        
        if prediction == 0:
            brake()
            print(f"{output} brake")
        elif prediction == 1:
            forward()
            print(f"{output} forward")
        elif prediction == 2:
            left()
            print(f"{output} forward + left")
        elif prediction == 3:
            right()
            print(f"{output} forward + right")
        

        if cv2.waitKey(25) & 0xFF == ord('q'):
            cv2.destroyAllWindows()
            break
            
if __name__ == '__main__':            
    main()

# Release the camera
# cap.release()


running ResNet auto-pilot...................
tensor([[-1.8793, -0.0467, -1.0650, -2.7000]], device='cuda:0') forward
tensor([[-1.5079, -0.4241, -1.6109, -2.0167]], device='cuda:0') forward
tensor([[-1.4756, -1.2799,  0.6121, -3.5421]], device='cuda:0') forward + left
tensor([[-1.9404, -1.2555,  0.9049, -4.0996]], device='cuda:0') forward + left
tensor([[-1.6699, -1.3379,  0.8339, -3.7035]], device='cuda:0') forward + left
tensor([[-1.4493, -1.3694,  1.1708, -3.9181]], device='cuda:0') forward + left
tensor([[-1.6686, -1.7963,  1.3447, -3.8827]], device='cuda:0') forward + left
tensor([[-1.7467, -1.3916,  0.8370, -3.9284]], device='cuda:0') forward + left
tensor([[-1.5100, -2.1169,  0.1777, -3.3079]], device='cuda:0') forward + left
tensor([[-2.4662, -1.1618,  1.1235, -3.8156]], device='cuda:0') forward + left
tensor([[-1.9950, -1.2252,  1.2930, -3.5290]], device='cuda:0') forward + left
tensor([[-2.3767, -1.1036,  0.9590, -3.4242]], device='cuda:0') forward + left
tensor([[-2.7983, -0.